---
- name: Converge
  hosts: all

  pre_tasks:
    - name: install jdk 8
      become: yes
      package:
        name: java-1.8.0-openjdk-headless
        state: present

    - name: install find
      become: yes
      package:
        name: findutils
        state: present

  roles:
    - role: gantsign.maven
      maven_version: '3.3.9'
      maven_install_dir: /opt/maven
    - ansible-role-maven-notifier
