---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-maven-notifier-fedora
    image: fedora:28
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: fedora

verifier:
  name: testinfra
  directory: ../default/tests
  lint:
    name: flake8
