---
- name: Converge
  hosts: all

  pre_tasks:
    - name: install jdk 8
      become: yes
      zypper:
        name: java-1_8_0-openjdk-headless
        state: present

  roles:
    - role: gantsign.maven
      maven_version: '3.3.9'
      maven_install_dir: /opt/maven
    - ansible-role-maven-notifier
