---
- name: Load version vars
  with_first_found:
    - "../vars/versions/{{ maven_notifier_version }}.yml"
    - ../vars/versions/default.yml
  include_vars: "{{ item }}"

- name: Assert version vars
  assert:
    that:
      - "maven_notifier_redis_sha256sum not in (None, '')"

- name: Create download directory
  file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: "{{ maven_notifier_download_dir }}"

- name: Download Maven Notifier
  get_url:
    url: "{{ maven_notifier_mirror }}/{{ maven_notifier_redis_filename }}"
    dest: "{{ maven_notifier_download_dir }}/{{ maven_notifier_redis_filename }}"
    sha256sum: "{{ maven_notifier_redis_sha256sum }}"
    force: false
    use_proxy: true
    validate_certs: true
    mode: 'u=rw,go=r'

- name: Install Maven Notifier
  become: yes
  copy:
    src: "{{ maven_notifier_download_dir }}/{{ maven_notifier_redis_filename }}"
    remote_src: yes
    dest: "{{ maven_notifier_maven_home }}/lib/ext/{{ maven_notifier_redis_filename }}"
    owner: root
    group: root
    mode: 'u=rw,go=r'
