---
- name: Load version vars
  tags: maven
  with_first_found:
    - ../vars/versions/{{ maven_notifier_version }}.yml
    - ../vars/versions/default.yml
  include_vars: "{{ item }}"

- name: Assert version vars
  tags: maven
  assert:
    that:
      - maven_notifier_redis_sha256sum not in (None, "")

- name: Include util get/put instructions
  tags: maven
  include: util.yml

- name: Install Maven Notifier
  tags: maven
  copy:
    src: "{{ util_persistent_data_path_remote }}/{{ maven_notifier_redis_filename }}"
    dest: "{{ maven_notifier_maven_home }}/lib/ext/{{ maven_notifier_redis_filename }}"
