---
- name: Load version vars
  tags: maven
  with_first_found:
    - "../vars/versions/{{ maven_notifier_version }}.yml"
    - ../vars/versions/default.yml
  include_vars: "{{ item }}"

- name: Assert version vars
  tags: maven
  assert:
    that:
      - "maven_notifier_redis_sha256sum not in (None, '')"

- name: Create local Ansible data directory
  tags: maven
  file:
    state: directory
    mode: 'u=rwx,go=rx'
    dest: "{{ local_ansible_data_path }}"

- name: Download Maven Notifier
  tags: maven
  get_url:
    url: "{{ maven_notifier_mirror }}/{{ maven_notifier_redis_filename }}"
    dest: "{{ local_ansible_data_path }}/{{ maven_notifier_redis_filename }}"
    sha256sum: "{{ maven_notifier_redis_sha256sum }}"
    force: false
    use_proxy: true
    validate_certs: true
    mode: 'u=rw,go=r'

- name: Install Maven Notifier
  tags: maven
  copy:
    src: "{{ local_ansible_data_path }}/{{ maven_notifier_redis_filename }}"
    dest: "{{ maven_notifier_maven_home }}/lib/ext/{{ maven_notifier_redis_filename }}"
