---
- name: Converge
  hosts: all

  pre_tasks:
    - name: install OpenJDK PPA
      apt_repository:
        repo: ppa:openjdk-r/ppa

    - name: install jdk 8
      become: yes
      apt:
        name: openjdk-8-jdk
        state: present

    - name: update ca-certificates
      become: yes
      command: update-ca-certificates --fresh
      changed_when: no

  roles:
    - role: gantsign.maven
      maven_version: '3.3.9'
      maven_install_dir: /opt/maven
    - ansible-role-maven-notifier
