---
- name: Converge
  hosts: all

  pre_tasks:
    - name: install jdk 7
      become: yes
      apt:
        name: openjdk-7-jdk
        state: present

  roles:
    - role: gantsign.maven
      maven_version: '3.3.9'
      maven_install_dir: /opt/maven
    - ansible-role-maven-notifier
