---
- name: Converge
  hosts: all

  pre_tasks:
    - name: update apt cache
      apt:
        update_cache: yes
      changed_when: no

    # Travis CI doesn't provide all the Debian dependencies for the full JDK.
    - name: install jre-headless 11
      become: yes
      apt:
        name: openjdk-11-jre-headless
        state: present

  roles:
    - role: gantsign.maven
      maven_version: '3.3.9'
      maven_install_dir: /opt/maven
    - ansible-role-maven-notifier
