---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-maven-notifier-centos-6
    image: centos:6

provisioner:
  name: ansible
  lint:
    name: ansible-lint

scenario:
  name: centos-min

verifier:
  name: testinfra
  directory: ../default/tests
  lint:
    name: flake8
