---
- name: Converge
  hosts: all

  roles:
    - role: gantsign.java
      java_version: '8'
    - role: gantsign.maven
      maven_version: '3.3.9'
      maven_install_dir: /opt/maven
    - ansible-role-maven-notifier
