---
- name: Converge
  hosts: all

  pre_tasks:
    # Travis CI doesn't provide all the Debian dependencies for the full JDK.
    - name: install jre-headless 7
      become: yes
      apt:
        name: openjdk-7-jre-headless
        state: present

  roles:
    - role: gantsign.maven
      maven_version: '3.3.9'
      maven_install_dir: /opt/maven
    - ansible-role-maven-notifier
